<?php

declare(strict_types=1);

namespace MageSec;

final class IssueManager
{
    private const MARKER = '<!-- magesec-status -->';
    private const TITLE = 'MageSec Security Status';

    public function __construct(private readonly GitHubClient $client)
    {
    }

    public function sync(array $project, array $matches, string $token): array
    {
        $repository = getenv('GITHUB_REPOSITORY') ?: '';
        if ($repository === '') {
            return $this->skipped('GITHUB_REPOSITORY is not available.');
        }

        if ($token === '') {
            return $this->skipped('github_token is required for auto_issue.');
        }

        $body = $this->renderBody($project, $matches);
        $existing = $this->findExistingIssue($repository);

        if ($existing !== null) {
            $number = (int) $existing['number'];
            $updated = $this->client->requestJson(
                'PATCH',
                sprintf('https://api.github.com/repos/%s/issues/%d', $repository, $number),
                [
                    'title' => self::TITLE,
                    'body' => $body,
                    'state' => 'open',
                ]
            );

            return [
                'created' => 0,
                'number' => $number,
                'url' => $updated['html_url'] ?? null,
                'skipped_reason' => null,
            ];
        }

        $created = $this->client->requestJson(
            'POST',
            sprintf('https://api.github.com/repos/%s/issues', $repository),
            [
                'title' => self::TITLE,
                'body' => $body,
            ]
        );

        return [
            'created' => 1,
            'number' => $created['number'] ?? null,
            'url' => $created['html_url'] ?? null,
            'skipped_reason' => null,
        ];
    }

    public function renderBody(array $project, array $matches): string
    {
        $lines = [
            self::MARKER,
            '',
            sprintf('Edition: %s', $project['edition'] ?? 'unknown'),
            sprintf('Package: %s', $project['edition_package'] ?? 'unknown'),
            sprintf('Version: %s', $project['version'] ?? 'unknown'),
            '',
        ];

        if ($matches === []) {
            $lines[] = 'No matched vulnerabilities at the current severity threshold.';
            $lines[] = '';
            $lines[] = '_Generated by MageSec._';
            return implode("\n", $lines);
        }

        $lines[] = '| CVE | Name | Severity | Status |';
        $lines[] = '| --- | --- | --- | --- |';

        foreach ($matches as $match) {
            $lines[] = sprintf(
                '| %s | %s | %s | %s |',
                $match['cve'],
                str_replace('|', '\\|', $match['title']),
                strtoupper($match['severity']),
                $this->statusLabel($match['selected_remediation'])
            );
        }

        $lines[] = '';
        $lines[] = '_Generated by MageSec._';

        return implode("\n", $lines);
    }

    private function findExistingIssue(string $repository): ?array
    {
        $issues = $this->client->requestJson(
            'GET',
            sprintf('https://api.github.com/repos/%s/issues?state=all&per_page=100', $repository)
        );

        foreach ($issues as $issue) {
            if (!is_array($issue) || isset($issue['pull_request'])) {
                continue;
            }

            $title = (string) ($issue['title'] ?? '');
            $body = (string) ($issue['body'] ?? '');
            if ($title === self::TITLE || str_contains($body, self::MARKER)) {
                return $issue;
            }
        }

        return null;
    }

    private function statusLabel(?array $remediation): string
    {
        if (!is_array($remediation)) {
            return 'Investigation required';
        }

        return match ($remediation['type'] ?? null) {
            'composer-update' => 'Official patch available',
            'composer-require' => 'Community extension required',
            'patch' => 'Community patch required',
            default => 'Remediation planned',
        };
    }

    private function skipped(string $reason): array
    {
        return [
            'created' => 0,
            'number' => null,
            'url' => null,
            'skipped_reason' => $reason,
        ];
    }
}