<?php

declare(strict_types=1);

namespace MageSec;

use RuntimeException;

final class PrManager
{
    public function __construct(private readonly GitHubClient $client)
    {
    }

    public function createOrUpdateAggregatePr(string $workspace, array $matches, string $token): array
    {
        $repository = getenv('GITHUB_REPOSITORY') ?: '';
        if ($repository === '') {
            return [
                'created' => 0,
                'number' => null,
                'url' => null,
                'skipped_reason' => 'GITHUB_REPOSITORY is not available.',
            ];
        }

        if (!is_dir($workspace . DIRECTORY_SEPARATOR . '.git')) {
            return [
                'created' => 0,
                'number' => null,
                'url' => null,
                'skipped_reason' => 'Workspace is not a git checkout.',
            ];
        }

        if ($token === '') {
            return [
                'created' => 0,
                'number' => null,
                'url' => null,
                'skipped_reason' => 'github_token is required for auto_pr.',
            ];
        }

        $branch = 'magesec/auto-remediation';
        $base = getenv('GITHUB_REF_NAME') ?: $this->defaultBranch($repository);

        $this->runCommand(['git', 'config', 'user.name', 'github-actions[bot]'], $workspace);
        $this->runCommand(['git', 'config', 'user.email', '41898282+github-actions[bot]@users.noreply.github.com'], $workspace);
        $this->runCommand(['git', 'checkout', '-B', $branch], $workspace);
        $this->runCommand(['git', 'add', '-A'], $workspace);

        [$statusCode] = $this->runCommand(['git', 'diff', '--cached', '--quiet'], $workspace, true);
        if ($statusCode === 0) {
            return [
                'created' => 0,
                'number' => null,
                'url' => null,
                'skipped_reason' => 'No staged changes to include in a pull request.',
            ];
        }

        $title = 'MageSec remediation updates';
        $body = $this->buildPrBody($matches);

        $this->runCommand(['git', 'commit', '-m', $title], $workspace);
        $remoteUrl = sprintf('https://x-access-token:%s@github.com/%s.git', $token, $repository);
        $this->runCommand(['git', 'remote', 'set-url', 'origin', $remoteUrl], $workspace);
        $this->runCommand(['git', 'push', '--force-with-lease', 'origin', $branch], $workspace);

        [$owner] = explode('/', $repository, 2);
        $existing = $this->client->requestJson(
            'GET',
            sprintf('https://api.github.com/repos/%s/pulls?state=open&head=%s:%s', $repository, $owner, rawurlencode($branch))
        );

        if ($existing !== [] && isset($existing[0]['number'])) {
            $number = (int) $existing[0]['number'];
            $updated = $this->client->requestJson(
                'PATCH',
                sprintf('https://api.github.com/repos/%s/pulls/%d', $repository, $number),
                ['title' => $title, 'body' => $body]
            );

            return [
                'created' => 0,
                'number' => $number,
                'url' => $updated['html_url'] ?? null,
                'skipped_reason' => null,
            ];
        }

        $created = $this->client->requestJson(
            'POST',
            sprintf('https://api.github.com/repos/%s/pulls', $repository),
            [
                'title' => $title,
                'head' => $branch,
                'base' => $base,
                'body' => $body,
            ]
        );

        return [
            'created' => 1,
            'number' => $created['number'] ?? null,
            'url' => $created['html_url'] ?? null,
            'skipped_reason' => null,
        ];
    }

    private function defaultBranch(string $repository): string
    {
        $repo = $this->client->requestJson('GET', sprintf('https://api.github.com/repos/%s', $repository));
        $defaultBranch = $repo['default_branch'] ?? null;
        if (!is_string($defaultBranch) || $defaultBranch === '') {
            throw new RuntimeException('Unable to determine the repository default branch.');
        }

        return $defaultBranch;
    }

    private function buildPrBody(array $matches): string
    {
        $lines = [
            'This pull request was generated by MageSec.',
            '',
            'Included vulnerabilities:',
        ];

        foreach ($matches as $match) {
            $lines[] = sprintf('- %s: %s (%s)', $match['cve'], $match['title'], strtoupper($match['severity']));
        }

        return implode("\n", $lines);
    }

    private function runCommand(array $command, string $cwd, bool $allowFailure = false): array
    {
        $descriptorSpec = [
            0 => ['pipe', 'r'],
            1 => ['pipe', 'w'],
            2 => ['pipe', 'w'],
        ];

        $process = proc_open($command, $descriptorSpec, $pipes, $cwd);
        if (!is_resource($process)) {
            throw new RuntimeException('Unable to start git process.');
        }

        fclose($pipes[0]);
        $stdout = stream_get_contents($pipes[1]);
        fclose($pipes[1]);
        $stderr = stream_get_contents($pipes[2]);
        fclose($pipes[2]);
        $exitCode = proc_close($process);

        if ($exitCode !== 0 && !$allowFailure) {
            throw new RuntimeException(sprintf('Command failed: %s\n%s', implode(' ', $command), trim($stderr . PHP_EOL . $stdout)));
        }

        return [$exitCode, $stdout, $stderr];
    }
}